apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis
  namespace: demo
spec:
  version: 6.2.5
  replicas: 3
  sentinelRef: 
    name: sentinel-redis
    namespace: demo
  mode: Sentinel
  disableAuth: true
  # tls:
  #   issuerRef:
  #     apiGroup: cert-manager.io
  #     name: ca-issuer
  #     kind: Issuer
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  terminationPolicy: WipeOut
