apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-cluster
  namespace: demo
spec:
  version: 6.0.6
  mode: Cluster
  cluster:
    master: 3
    replicas: 2
  storageType: Durable
  storage:
    resources:
      requests:
        storage: "100Mi"
    storageClassName: "linode-block-storage-retain"
    accessModes:
    - ReadWriteOnce
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
  terminationPolicy: WipeOut
  # tls:
  #   issuerRef:
  #     apiGroup: cert-manager.io
  #     name: redis-ca-issuer
  #     kind: Issuer
  #   certificates:
  #   - alias: server
  #     subject:
  #       organizations:
  #       - kubedb:server
  #     dnsNames:
  #     - localhost
  #     ipAddresses:
  #     - "127.0.0.1"

